return {
    {'Townk/vim-autoclose'},
    {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
    {'neoclide/coc.nvim', branch = 'release'},
    {'junegunn/fzf', dir = '~/.fzf', run = './install --all'},
    {'junegunn/fzf.vim'},
    {'ggreer/the_silver_searcher'},
    {'tpope/vim-commentary'},
    {'tpope/vim-fugitive'},
    {'tpope/vim-surround'},
    {'mattn/emmet-vim'},
    {'Yggdroot/indentLine'},
    {'nvim-lualine/lualine.nvim'},
    {'nvim-tree/nvim-web-devicons'},
    {'vim-scripts/DeleteTrailingWhitespace'},
    {'alvan/vim-closetag'},
    {'fatih/vim-go', run = ':GoUpdateBinaries'},
    {'jgdavey/vim-blockle'},
    {'kchmck/vim-coffee-script'},
    {'HerringtonDarkholme/yats.vim'},
    {'leafOfTree/vim-vue-plugin'},
    {'tpope/vim-rails'},
    'rstacruz/vim-closer',
    {'tpope/vim-endwise'},
}

